# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: contact@mljar.com
author_name: MLJAR
has_binder: false
has_settings: false
kind: frontend
labextension_name: package-manager
project_short_description: A JupyterLab extension to list, remove and install python
    packages from pip.
python_name: package_manager
repository: https://github.com/mljar/package-manager
test: false

